apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: cleanup
      image: alpine:3.17
      script: |
        #!/bin/sh
        rm -rf /workspace/source/*

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test
spec:
  steps:
    - name: test
      image: python:3.9-slim
      workingDir: /workspace/source
      script: |
        #!/bin/sh
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        nosetests -v --with-spec --spec-color --with-coverage --cover-package=service